### ISSUE TITLE
Use native libs from mavencentral?

### ISSUE THREAD

**Issue by ghost** [ekx/GitLabAndroid#10]
Could the native libs be pulled from mavenCentral directly from the build.gradle, like https://github.com/Uncodin/bypass/blob/master/platform/android/README.md suggests?

**Comment by robinpaulson** [comment]
Is it possible to use this fork of bypass instead? https://github.com/codlab/bypass_gradle

**Comment by robinpaulson** [comment]
@ekx could you check out the version of bypass i referenced in the comment above? cheers
