### ISSUE TITLE
Unable to login on HTTPS (with self-signed certificate)

### ISSUE THREAD

**Issue by chilladx** [ekx/GitLabAndroid#20]
When trying to login, either with email+password or with private token, I'm always getting a "Login failed" error message. The same action done in a web browser works like a charm (with a warning on the certificate).

**Comment by dAnjou** [comment]
This happens also for us even though our certificate isn't self-signed. Would it be possible to optionally just ignore the certificate check?

**Comment by robinpaulson** [comment]
@chilladx : It's possible to get a signed certificate for free from startssl.com, the root cert is included in most browsers

**Comment by XenGi** [comment]
@chilladx is this still an issue or can it be closed?

**Comment by chilladx** [comment]
oups, my bad, it's not an issue anymore, it can be closed.

**Comment by robinpaulson** [comment]
Also: https://letsencrypt.org/, coming soon and providing free, signed certificates
