### ISSUE TITLE
Put this app to F-Droid marcket

### ISSUE THREAD

**Issue by M0dM** [ekx/GitLabAndroid#4]
Hi,

I am not using google apps at all but still think your android app can interest me (I host my own gitlab on my vps server).
I am sure many people using gitlab on their own server think like me.
You should try to put your application on F-droid repositories ;).

Thanks for this app.

**Comment by IzzySoft** [comment]
@ekx 

> I will upload all new releases here on Github

Looks like you've stopped that years ago: the last release here is from 2014, while Playstore reports one from 2016. Planning a refresh – or is the project been given up?

**Comment by ekx** [comment]
The Playstore version from 2016 just changed the Icon (This was a request from the GitLab team). This project has been dead for a long time. Check out this fork which is still being developed. https://github.com/Commit451/LabCoat

**Comment by IzzySoft** [comment]
Thanks for the fast response, @ekx – I see they even have a quite up-to-date version at F-Droid.

May I suggest adding a related note to the main `README.md` file to point that out? Avoids unnecessary stir-ups in the issues :wink:

```Markdown
> **Note:** this project is no longer maintained. Development [continues here](https://github.com/Commit451/LabCoat).
```
